version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
  keycloak:
      image: keycloak-path
      build:
        context: keycloak_docker
        args:
          URL_PATH: keycloak/
      environment:
        PROXY_ADDRESS_FORWARDING: "true"
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: "${DB_PASSWORD}"
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: "${ADMIN_PASSWORD}"
      ports:
        - 8080:8080
      depends_on:
        - postgres